### ISSUE TITLE
RiskModelBuilder 

### ISSUE THREAD

**Issue by shwdmsh** [kinnamon-lab/PRISM#1]
Hi,I first build a risk model as follows:
(1).First, mkdir RiskModelBuilder
(2).Then , create a SNP information file named ./RiskModelBuilder/[model 001]_SNPs.dat
the context of the [model 001]_SNPs.dat file :
modelID rsID    sourcePub       allele1 allele2 orientRs        allele2Freq     allele2LnHR
model001        206081  Pubmed  C       T       Forward 0.170128        0.8
model001        206097  Pubmed  G       T       Forward 0.440895        0.9
model001        206112  Pubmed  A       T       Forward 0.390775        1
(3)Third, create an annual incidence file named ./RiskModelBuilder/[model_001]_annInc.dat
the context of the [model_001]_annInc.dat:
modelID ageYrs  annInc
model001        50      0.05
(4). java -cp prism-1.0.0.jar edu.osumc.prism.RiskModelBuilder -m model001
However , I don't get risk model object files,which are binary files that have the extension *.rmo.

**Comment by ddkinnamon** [comment]
The main problem appears to be that you are specifying a file prefix that is not found (model001 vs. model_001). The command that you specified will be looking for `model001_SNPs.dat` and `model001_annInc.dat`. When it doesn't find them, the program just exits quietly. Please run `java -cp prism-1.0.0.jar edu.osumc.prism.RiskModelBuilder -h` and read the usage instructions to make sure that your command is correct.

Also, beware that the input file examples given above do not follow the instructions provided in the [README](https://github.com/kinnamon-lab/PRISM/blob/master/README.md) and so will produce errors. In particular:
1. rsID values must be specified as "rs206081".
2. Annual incidences must be specified for each consecutive year from age 0.

I also noticed that the header should be "allele2lnHR" (note lower case), which is not correct in our documentation. Correct the header in your file, and I will correct the README. After correcting all of these issues, I was able to get `model001.rmo` from running `RiskModelBuilder`.

**Comment by ddkinnamon** [comment]
README.md error fixed in db01f44c2237679581b003b166325644bc259583.

**Comment by shwdmsh** [comment]
Dear , ddkinnamon :Thank you for your help!
Now,I meet the error as follows:
2019-01-28 22:03:56,077 edu.osumc.prism.RiskModelBuilder [ERROR] Exception thrown. Details:
java.util.NoSuchElementException: null
at java.util.Scanner.throwFor(Scanner.java:862) ~[?:1.8.0_141]
at java.util.Scanner.next(Scanner.java:1371) ~[?:1.8.0_141]
at edu.osumc.prism.RiskModelBuilder.parseInputFiles(RiskModelBuilder.java:339) ~[prism-1.0.0.jar:1.0.0]
at edu.osumc.prism.RiskModelBuilder.main(RiskModelBuilder.java:484) [prism-1.0.0.jar:1.0.0]
java.util.NoSuchElementException
(1).I edited model001_SNPs.dat file,
now the context of  the model001_SNPs.dat file :
modelID	rsID	sourcePub	allele1	allele2	orientRs	allele2Freq	allele2lnHR
model001	rs206081	Pubmed	C	T	Forward	0.170128	0.8
model001	rs206097	Pubmed	G	T	Forward	0.440895	0.9
model001	rs206112	Pubmed	A	T	Forward	0.390775	1
(2).I edited model001_annInc.dat file,
now the context of the model001_annInc.dat file :
modelID	ageYrs	annInc
model001	0	0
model001	1	0
model001	2	0
model001	3	0
model001	4	0.08
model001	5	0.08
model001	6	0.1
model001	7	0.1
model001	8	0.1
model001	9	0.2
model001	10	0.2
model001	11	0.3
model001	12	0.3
model001	13	0.3
model001	14	0.3
model001	15	0.4
model001	16	0.4
model001	17	0.4
model001	18	0.5
model001	19	0.5
model001	20	0.5
